# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/
name = "cloudflare"
main = "src/index.ts"
compatibility_date = "2025-01-21"

[observability]
enabled = true

# Smart Placement
# Docs: https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
# Uncomment the following section to enable smart placement
# [placement]
# mode = "smart"

# Bindings
# Bindings allow your Worker to interact with resources on the Cloudflare Developer Platform.
# https://developers.cloudflare.com/workers/runtime-apis/bindings/

# Environment Variables
# https://developers.cloudflare.com/workers/wrangler/configuration/#environment-variables
# Uncomment and set your environment variables
# [vars]
# MY_VARIABLE = "production_value"
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYzJlOTkxMTQtMTU1ZS00YTQ4LWI3NDUtOTJkMTQyNWVlM2NhIiwidGVuYW50X2lkIjoiZWE4MDczYjg3NzQyY2I1OGYxMzYzNTlhZTBiMDBkODYxMjM1YjY1NzJlNzM5YWQyMWNlNDZhNWI4MTA0OTA3MyIsImludGVybmFsX3NlY3JldCI6Ijk4NTg0MDdjLTFkNWMtNDU5ZS1iYjY0LWQ1NzI4YzM0NDU0OSJ9.zovrJIzoLIiF0SaPMrnWZH5j7Oj10eYC8Exa2Xt_Nqs"

# Note: Use secrets to store sensitive data.
# https://developers.cloudflare.com/workers/configuration/secrets/

# Static Assets
# https://developers.cloudflare.com/workers/static-assets/binding/
# Uncomment and configure for static assets
# [assets]
# directory = "./public/"
# binding = "ASSETS"

# Service Bindings
# Communicate between multiple Workers
# https://developers.cloudflare.com/workers/wrangler/configuration/#service-bindings
# Uncomment and configure service bindings
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"
